config/routes.rb
MyGallery::Application.routes.draw do
  root 'galleries#new'
  resources :galleries
  resources :images

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new gallery_params

    if @gallery.save
      redirect_to @gallery
    end
  end

  def show
    @gallery = Gallery.find params[:id]
    @image = Image.new
  end

  private

  def gallery_params
    params.require(:gallery).permit :name
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
    @gallery = Gallery.find image_params[:gallery_id]
    @image = Image.new image_params

    if @image.save
      redirect_to @gallery
    end
  end

  private

  def image_params
    params.require(:image).permit :filepicker_url, :gallery_id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_controller_helper.rb
module GalleryControllerHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/views/galleries/new.html.erb
<h2>Create new gallery</h2>

<%= form_for @gallery do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit "Create gallery" %>
<% end %>

app/views/galleries/show.html.erb
<h2><%= @gallery.name %></h2>

<p>Share this gallery: <%= link_to gallery_url(@gallery) %></p>

<%= form_for @image do |f| %>
  <%= f.hidden_field :gallery_id, value: @gallery.id %>

  <div>
    <%= f.label :filepicker_url, "Upload a image:" %>
    <%= f.filepicker_field :filepicker_url, name: "image[filepicker_url]"
    %>
  </div>

  <%= f.submit "Add a image" %>
<% end %>

<ul>
  <% @gallery.images.each do |image| %>
    <li>
    <%= filepicker_image_tag image.filepicker_url, w: 160, h: 160, fit: 'clip' %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGallery</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= filepicker_js_include_tag %>
</body>
</html>